//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeID { get; set; }

        [Required(ErrorMessage ="This filed is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This filed is required")]
        public string Position { get; set; }

        [Required(ErrorMessage = "This filed is required")]
        public string Office { get; set; }

        [Required(ErrorMessage = "This filed is required")]
        public Nullable<int> Salary { get; set; }

        [Display(Name="Image")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Employee()
        {
            ImagePath = "~/AppFiles/Images/upload.png";
        }
    }
}
